class Joint:
  def __init__(self) -> None:
      
      Hip = 3
      RightUpLeg = 6
      RightLeg = 9
      RightFoot = 12
      LeftUpLeg = 15
      LeftLeg = 18
      LeftFoot = 21
      Spine = 24
      Spine1 = 27
      Spine2 = 30
      Spine3 = 33
      Neck = 36
      Head = 39
      RightShoulder = 42
      RightArm = 45
      RightForeArm = 48
      RightHand = 51
      RightHandThumb1 = 54
      RightHandThumb2 = 57
      RightHandThumb3 = 60
      RightInHand = 63
      RightHandIndex1 = 66
      RightHandIndex2 = 69
      RightHandIndex3 = 72
      RightInHandMiddle = 75
      RightHandMiddle1 = 78
      RightHandMiddle2 = 81
      RightHandMiddle3 = 84
      RightInHandRing = 87
      RightHandRing1 = 90
      RightHandRing2 = 93
      RightHandRing3 = 96
      RightInHandPinky = 99
      RightHandPinky1 = 102
      RightHandPinky2 = 105
      RightHandPinky3 = 108
      LeftShoulder = 111
      LeftArm = 114
      LeftForeArm = 117
      LeftHand = 120
      LeftHandThumb1 = 123
      LeftHandThumb2 = 126
      LeftHandThumb3 = 129
      LeftInHandIndex = 132
      LeftHandIndex1 = 135
      LeftHandIndex2 = 138
      LeftHandIndex3 = 141
      LeftInHandMiddle = 144
      LeftInHandMiddle1 = 147
      LeftInHandMiddle2 = 150
      LeftInHandMiddle3 = 153
      LeftInHandRing = 156
      LeftHandRing1 = 159
      LeftHandRing2 = 162
      LeftHandRing3 = 165
      LeftInHandPinky = 168
      LeftHandPinky1 = 171
      LeftHandPinky2 = 174
      LeftHandPinky3 = 177

      self.hip = {'j_num': Hip, 'j_name': 'hip'}
      self.right_up_leg = {'j_num': RightUpLeg, 'j_name': 'rightupLeg'}
      self.right_leg = {'j_num': RightLeg, 'j_name': 'rightleg'}
      self.right_foot = {'j_num': RightFoot, 'j_name': 'rightfoot'}
      self.left_up_leg = {'j_num': LeftUpLeg, 'j_name': 'leftupLeg'}
      self.left_leg = {'j_num': LeftLeg, 'j_name': 'leftleg'}
      self.left_foot = {'j_num': LeftFoot, 'j_name': 'leftfoot'}
      self.spine = {'j_num': Spine, 'j_name': 'spine'}
      self.spine_1 = {'j_num': Spine1, 'j_name': 'spine1'}
      self.spine_2 = {'j_num': Spine2, 'j_name': 'spine2'}
      self.spine_3 = {'j_num': Spine3, 'j_name': 'spine3'}
      self.neck = {'j_num': Neck, 'j_name': 'neck'}
      self.head = {'j_num': Head, 'j_name': 'head'}
      self.right_shoulder = RightShoulder{'j_num': , 'j_name': ''}
      self.right_arm = RightArm{'j_num': , 'j_name': ''}
      self.right_fore_arm = RightForeArm{'j_num': , 'j_name': ''}
      self.right_hand = RightHand{'j_num': , 'j_name': ''}
      self.right_hand_thumb1 = RightHandThumb1{'j_num': , 'j_name': ''}
      self.right_hand_thumb2 = RightHandThumb2{'j_num': , 'j_name': ''}
      self.right_hand_thumb3 = RightHandThumb3{'j_num': , 'j_name': ''}
      self.right_in_hand = RightInHand{'j_num': , 'j_name': ''}
      self.right_hand_index1 = RightHandIndex1{'j_num': , 'j_name': ''}
      self.right_hand_index2 = RightHandIndex2{'j_num': , 'j_name': ''}
      self.right_hand_index3 = RightHandIndex3{'j_num': , 'j_name': ''}
      self.right_in_hand_middle = RightInHandMiddle{'j_num': , 'j_name': ''}
      self.right_hand_middle1 = RightHandMiddle1{'j_num': , 'j_name': ''}
      self.right_hand_middle2 = RightHandMiddle2{'j_num': , 'j_name': ''}
      self.right_hand_middle3 = RightHandMiddle3{'j_num': , 'j_name': ''}
      self.right_in_hand_ring = RightInHandRing{'j_num': , 'j_name': ''}
      self.right_hand_ring1 = RightHandRing1{'j_num': , 'j_name': ''}
      self.right_hand_ring2 = RightHandRing2{'j_num': , 'j_name': ''}
      self.right_hand_ring3 = RightHandRing3{'j_num': , 'j_name': ''}
      self.right_in_hand_pinky = RightInHandPinky{'j_num': , 'j_name': ''}
      self.right_hand_pinky1 = RightHandPinky1{'j_num': , 'j_name': ''}
      self.right_hand_pinky2 = RightHandPinky2{'j_num': , 'j_name': ''}
      self.right_hand_pinky3 = RightHandPinky3{'j_num': , 'j_name': ''}
      self.left_shoulder = LeftShoulder{'j_num': , 'j_name': ''}
      self.left_arm = LeftArm{'j_num': , 'j_name': ''}
      self.left_fore_arm = LeftForeArm{'j_num': , 'j_name': ''}
      self.left_hand = LeftHand{'j_num': , 'j_name': ''}
      self.left_hand_thumb1 = LeftHandThumb1{'j_num': , 'j_name': ''}
      self.left_hand_thumb2 = LeftHandThumb2{'j_num': , 'j_name': ''}
      self.left_hand_thumb3 = LeftHandThumb3{'j_num': , 'j_name': ''}
      self.left_in_hand_index = LeftInHandIndex{'j_num': , 'j_name': ''}
      self.left_hand_index1 = LeftHandIndex1{'j_num': , 'j_name': ''}
      self.left_hand_index2 = LeftHandIndex2{'j_num': , 'j_name': ''}
      self.left_hand_index3 = LeftHandIndex3{'j_num': , 'j_name': ''}
      self.left_in_hand_middle = LeftInHandMiddle{'j_num': , 'j_name': ''}
      self.left_in_hand_middle1 = LeftInHandMiddle1{'j_num': , 'j_name': ''}
      self.left_in_hand_middle2 = LeftInHandMiddle2{'j_num': , 'j_name': ''}
      self.left_in_hand_middle3 = LeftInHandMiddle3{'j_num': , 'j_name': ''}
      self.left_in_hand_ring = LeftInHandRing{'j_num': , 'j_name': ''}
      self.left_hand_ring1 = LeftHandRing1{'j_num': , 'j_name': ''}
      self.left_hand_ring2 = LeftHandRing2{'j_num': , 'j_name': ''}
      self.left_hand_ring3 = LeftHandRing3{'j_num': , 'j_name': ''}
      self.left_in_hand_pinky = LeftInHandPinky{'j_num': , 'j_name': ''}
      self.left_hand_pinky1 = LeftHandPinky1{'j_num': , 'j_name': ''}
      self.left_hand_pinky2 = LeftHandPinky2{'j_num': , 'j_name': ''}
      self.left_hand_pinky3 = LeftHandPinky3{'j_num': , 'j_name': ''}

